version: "3.8"

services:
  geth:
    image: ethereum/client-go:v1.14.9
    pull_policy: always
    container_name: geth
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: [ "CMD-SHELL", "geth --datadir=/data attach  --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - /data/geth:/data
    command:
      - --datadir=/data
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,engine,admin
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/data/jwt.hex
      - --authrpc.port=8551
      - --txlookuplimit=0
      - --maxpeers=300
      - --mainnet
      - --syncmode=snap
      - --db.engine=leveldb
      - --metrics
      - --pprof
      - --pprof.addr=0.0.0.0
      - --pprof.port=6060
  lighthouse:
    image: sigp/lighthouse:v5.3.0
    pull_policy: always
    container_name: lighthouse
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - /data/lighthouse:/data
      - /data/geth:/geth
    depends_on:
      geth:
        condition: service_healthy
    ports:
      - 8080:8080
      - 9000:9000
      - 9000:9000/udp
    command:
      - lighthouse
      - bn
      - --network=mainnet
      - --datadir=/data
      - --execution-endpoint=http://geth:8551
      - --execution-jwt=/geth/jwt.hex
      - --http
      - --http-allow-origin=*
      - --http-port=8080
      - --http-address=0.0.0.0
      - --metrics
      - --metrics-allow-origin=*
      - --metrics-port=9090
      - --metrics-address=0.0.0.0
      - --checkpoint-sync-url=https://beaconstate.ethstaker.cc
      - --slots-per-restore-point=2048
      - --historic-state-cache-size=1
      - --purge-db
      - --disable-backfill-rate-limiting
